server:
  port: 8080
  tomcat:
    max-http-form-post-size: 200MB
    max-swallow-size: 200MB
db:
  webui:
    hikari:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.234.129:1433;databaseName=webui
      username: sa
      password: S4P4ssw0rd
      max-pool-size: 10
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect
      show-sql: true
      format-sql: true
ldap:
  base: OU=Avrist Users,DC=avrist,DC=net
  url: LDAP://10.50.1.10
  username: DAPP005@avrist.net
  password: '#Avr!st46$^'

webconfig:
  filter:
    unfiltered:
      path:
        - "/favicon.ico"
        - "/dist/**"
        - "/css/**"
        - "/js/**"
        - "/plugins/**"
        - "/login"
        - "/dashboard"
        - "/api/v1/login/validate"
        - "/api/v1/login/request"


